### PR TITLE
Use pre-commit for linting

### PR DESCRIPTION
**Pull request by sublime-coleslaw**
#3159 

This adds a dev dependency for pre-commit, and a basic pre-commit configuration for linting with ruff. The second commit fixes the various issues that pre-commit complained about.

Tests still aren't run using pre-commit, and none of the github actions have been switched to use pre-commit. I'm not sure if that would be a good idea since pre-commit usually isn't used to run tests.

### CODE REVIEW

**Review by kantord — CHANGES_REQUESTED** [review]
Looks good to me, but this file needs to be changed as well to make the pipeline work: https://github.com/LibreLingo/LibreLingo/blob/main/.github/workflows/python.yml

**Comment by sublime-coleslaw** [comment]
I added ruff as a poetry dependency and changed the workflow to use ruff instead of black/pylint

**Comment by kantord** [comment]
hi @sublime-coleslaw it seems like it is still failing? https://github.com/LibreLingo/LibreLingo/actions/runs/6958213826/job/19029305201?pr=3177

are you having trouble running these checks in your fork? maybe I could help you with that

**Comment by sublime-coleslaw** [comment]
whoops! forgot to check that command locally before pushing. unfortunately github doesn't seem to want to run any of the workflows in my fork on push, and i can't create a PR in my fork. if you know of a workaround, i'd appreciate help getting it to run :)

**Comment by kantord** [comment]
> github doesn't seem to want to run any of the workflows in my fork on push, and i can't create a PR in my fork. if you know of a workaround, i'd appreciate help getting it to run :)

If I understand correctly, it should be enough for you to [enable Github Actions in your fork](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository), and then it should run the github action using your fork. But that probably does not apply to the "pull request" trigger, only to the "push" trigger I guess. (I'm not sure about it)

So I think this might actually be my fault, as it seems the `push` trigger is not enabled in the repo. I think

**Pull request closed without merging**
