### PR TITLE
Reduce course load time by loading modules in parallel

### PR DESCRIPTION
**Pull request by dimkard**

### CODE REVIEW

**Comment by kantord** [comment]
nice!

**Review by kantord — CHANGES_REQUESTED** [review]
@dimkard can you please run `poetry run black apps` and commit the changes? Looks like that's the only CI failure: https://kantord.semaphoreci.com/workflows/a294a9ab-56cc-4ecd-8ad0-7608c563417d?pipeline_id=7e57d5e5-d03f-490c-93a7-8391fa5a38b1

**Comment by kantord** [comment]
it looks like the pytest test cases now never completely finish :thinking:

**Comment by dimkard** [comment]
Not sure what happens, we can abandon this workaround and focus on the root cause #2314. :thinking:

**Comment by kantord** [comment]
> Not sure what happens, we can abandon this workaround and focus on the root cause #2314. thinking

I will also try to look into this because I would say that it would be nice to use both solutions in combination in order to try to bring the loading times down to around 1s in order to be able to develop tools that work with the course data almost instantly

**Comment by kantord** [comment]
closing this as seemingly there's no more work being done here. feel free to reopen if you restart the work

**Pull request closed without merging**
