### PR TITLE
refactor(tests): move load_dictionary tests into a separated file

### PR DESCRIPTION
**Pull request by qbecb1zen**
# edit this template according to your needs, delete anything that's not relevant

## Description

_Short description of the changes you made. Not necessary if it's clear based on the issue you're resolving_

**Is this related to any open issue(s)?**

fixes #{issue id here}

**Is there anything you need help with to get this PR merged?**

_..._

## Checklist

Don't worry if you haven't done everything on this checklist. Simply create your PR, and make sure everything is done later,
or ask for help if you don't know how to do it.

- [ ] The CI is passing
- [ ] I tested my implementation manually
- [ ] I wrote new tests to test my code, or updated existing tests to test my changes

### CODE REVIEW

**Review by kantord — CHANGES_REQUESTED** [review]
you tests are failing in the CI, take a loot at: https://kantord.semaphoreci.com/jobs/b19dddac-649e-44f4-8301-bcc8d1a4eb54

**Comment by qbecb1zen** [comment]
> you tests are failing in the CI, take a loot at: https://kantord.semaphoreci.com/jobs/b19dddac-649e-44f4-8301-bcc8d1a4eb54

yes, i just didn't had time to check for them :) !

**Comment by qbecb1zen** [comment]
@kantord do you have an idea why the CI do not start ? 

normally i fixed the tests 😅

**Comment by kantord** [comment]
Hi @qbecb1zen  you have a code style issue that is causing the CI to fail. In order to fix, please run 

```bash
poetry run black apps
```

**Review by kantord — CHANGES_REQUESTED** [review]
see my latest comment

**Comment by kantord** [comment]
Hi @qbecb1zen can you please resolve the conflicts?

**Comment by qbecb1zen** [comment]
> Hi @qbecb1zen can you please resolve the conflicts?

Hi, as soon as i have a moment, i will resolve all issues in this branch to make it ready !

**Comment by kantord** [comment]
> > Hi @qbecb1zen can you please resolve the conflicts?
> 
> Hi, as soon as i have a moment, i will resolve all issues in this branch to make it ready !

thank you so much @qbecb1zen and let me know if you need any help from me

**Comment by qbecb1zen** [comment]
> > > Hi @qbecb1zen can you please resolve the conflicts?
> > 
> > 
> > Hi, as soon as i have a moment, i will resolve all issues in this branch to make it ready !
> 
> thank you so much @qbecb1zen and let me know if you need any help from me

it's waiting for you haha!

**Comment by kantord** [comment]
thank you @qbecb1zen

**Pull request merged**
