### PR TITLE
Issue-2499: fix 2 instances of lines that are too long

### PR DESCRIPTION
**Pull request by rsk2**
To resolve issue #2499

### CODE REVIEW

**Comment by kantord** [comment]
Look good, thank you @rsk2 ! :tada: :100: :rocket:

**Review by kantord — CHANGES_REQUESTED** [review]
Opps. I was wrong. It _looks_ good, but there's one problem: the tests are failing

https://github.com/LibreLingo/LibreLingo/actions/runs/3314578776/jobs/5481836901

Please fix the failing tests :pray: otherwise it cannot be merged

**Comment by rsk2** [comment]
> Opps. I was wrong. It _looks_ good, but there's one problem: the tests are failing
> 
> https://github.com/LibreLingo/LibreLingo/actions/runs/3314578776/jobs/5481836901
> 
> Please fix the failing tests 🙏 otherwise it cannot be merged

@kantord those tests are failing because I formatted the expected output in order to reduce the line length . Any suggestion on how to fix this?

**Comment by kantord** [comment]
@rsk2 looks like this could be the issue: https://stackoverflow.com/questions/28805567/line-continuation-wrapping-in-doctest it seems like doctest actually tests that the output strings are equivalent, that's why this is an error, because in the output, the whitespace is not there.

But it seems like it should be possible to instruct doctest to normalize whitespace, which would fix this problem. Looks like you can add this configuration option in order to fix it: https://docs.pytest.org/en/7.1.x/how-to/doctest.html#using-doctest-options

**Comment by rsk2** [comment]
> @rsk2 looks like this could be the issue: https://stackoverflow.com/questions/28805567/line-continuation-wrapping-in-doctest it seems like doctest actually tests that the output strings are equivalent, that's why this is an error, because in the output, the whitespace is not there.
> 
> But it seems like it should be possible to instruct doctest to normalize whitespace, which would fix this problem. Looks like you can add this configuration option in order to fix it: https://docs.pytest.org/en/7.1.x/how-to/doctest.html#using-doctest-options

@kantord Thanks. I have made the suggested changes

**Review by kantord — APPROVED** [review]

**Comment by kantord** [comment]
Good job @rsk2 thank you!!! :100:  it's merged! 

@allcontributors please add @rsk2 for code

**Pull request merged**
