### PR TITLE
WIP: Add Esperanto from Spanish course

### PR DESCRIPTION
**Pull request by jorgesumle**
Hi, I'm translating the basic course Spanish from English into Esperanto from Spanish, but I got the following error when running `yarn exportAllCourses`:

```
 yarn exportAllCourses
yarn run v1.22.19
$ ./scripts/exportAllYamlCourses.sh
✅ Exported course basque-from-english
✅ Exported course brazilian-portuguese-from-english
⏳ Exporting course esperanto-from-spanishTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jorge/.cache/pypoetry/virtualenvs/librelingo-json-export-KgEiUmpX-py3.11/lib/python3.11/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.cache/pypoetry/virtualenvs/librelingo-json-export-KgEiUmpX-py3.11/lib/python3.11/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/jorge/.cache/pypoetry/virtualenvs/librelingo-json-export-KgEiUmpX-py3.11/lib/python3.11/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.cache/pypoetry/virtualenvs/librelingo-json-export-KgEiUmpX-py3.11/lib/python3.11/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/Repositorios/LibreLingo/apps/librelingo_json_export/librelingo_json_export/cli.py", line 27, in main
    course = load_course(input_path)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.cache/pypoetry/virtualenvs/librelingo-json-export-KgEiUmpX-py3.11/lib/python3.11/site-packages/librelingo_yaml_loader/yaml_loader.py", line 496, in load_course
    modules = _load_modules(path, raw_modules, dumb_course)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.cache/pypoetry/virtualenvs/librelingo-json-export-KgEiUmpX-py3.11/lib/python3.11/site-packages/librelingo_yaml_loader/yaml_loader.py", line 408, in _load_modules
    return [_load_module(Path(path) / module, course) for module in modules]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.cache/pypoetry/virtualenvs/librelingo-json-export-KgEiUmpX-py3.11/lib/python3.11/site-packages/librelingo_yaml_loader/yaml_loader.py", line 408, in <listcomp>
    return [_load_module(Path(path) / module, course) for module in modules]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.cache/pypoetry/virtualenvs/librelingo-json-export-KgEiUmpX-py3.11/lib/python3.11/site-packages/librelingo_yaml_loader/yaml_loader.py", line 400, in _load_module
    skills=_load_skills(path, skills, course),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.cache/pypoetry/virtualenvs/librelingo-json-export-KgEiUmpX-py3.11/lib/python3.11/site-packages/librelingo_yaml_loader/yaml_loader.py", line 365, in _load_skills
    return [_load_skill(Path(path) / "skills" / skill, course) for skill in skills]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.cache/pypoetry/virtualenvs/librelingo-json-export-KgEiUmpX-py3.11/lib/python3.11/site-packages/librelingo_yaml_loader/yaml_loader.py", line 365, in <listcomp>
    return [_load_skill(Path(path) / "skills" / skill, course) for skill in skills]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.cache/pypoetry/virtualenvs/librelingo-json-export-KgEiUmpX-py3.11/lib/python3.11/site-packages/librelingo_yaml_loader/yaml_loader.py", line 354, in _load_skill
    dictionary=_convert_mini_dictionary(data, course)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.cache/pypoetry/virtualenvs/librelingo-json-export-KgEiUmpX-py3.11/lib/python3.11/site-packages/librelingo_yaml_loader/yaml_loader.py", line 276, in _convert_mini_dictionary
    for item in raw_mini_dictionary[language_name]:
                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'esperanto'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My plan is to translate the course, and later, if it works fine, add more lessons. However, I need to solve this issue, so that I can test that my course doesn't produce any errors.

### CODE REVIEW

**Comment by kantord** [comment]
Hi @jorgesumle  it seems like this issue is because of an issue in the content within the course itself. This is because, in one of your skills, you use the word "esperanto", but it's not defined in the mini-dictionary. If you add add a definition for that word, the error should disappear. (but maybe there will be some other word(s) missing a definition)

**Comment by kantord** [comment]
by the way, if you wish I can create a repository for you on github

**Comment by jorgesumle** [comment]
I only use the word 'esperanto' in `course.yaml`. I don't think that is a skill. In any case, I don't know where to define it, because `course.yaml` is in the root directory.

```
$ grep -ir esperanto
course.yaml:    Name: esperanto
```

> by the way, if you wish I can create a repository for you on github under the LibreLingo organization. This would come with the added benefit that some developer tools (automatic setup and maintenance of some developer tools that make sure that the course can always be built) and that the course repo would be very easy to find from github.

> if you have some way to set up automatic synchronization then it is also possible to use this github repo as a proxy and do the actual development in your own git host. However, development on github (and perhaps later some other major hosts) will eventually have a GUI editor feature as well, where users will be able to contribute similarly to how they are able to do it on wikipedia

OK, as long as git push works, I'm fine with that.

**Comment by jorgesumle** [comment]
I solved the issue, but the audio questions don't work.

**Comment by kantord** [comment]
> I solved the issue, but the audio questions don't work.

that is because it needs further configuration, and for now it won't work for Esperanto. There's a planned project though to add support for this using Tatoeba and similar sources. For now that will need to be disabled

**Comment by kantord** [comment]
Hi @jorgesumle I created this repository within the LibreLingo organization and I invited you as maintainer (you should have received the invitation by email I think) https://github.com/LibreLingo/Librelingo-EO-from-ES

this is created using a template course which is basically based on the spanish course, but you should be able to more or less copy paste your files into it from your existing repo to fix that.

and in this repo the pipelines are configured already :heavy_check_mark:

**Comment by kantord** [comment]
closing due to no response, feel free to reopen or ask for assistance with your course @jorgesumle 

you can also schedule a call with me on https://app.harmonizely.com/harmonizely-uoicqk

**Pull request closed without merging**
