### PR TITLE
Add Docker files to /apps folder

### PR DESCRIPTION
**Pull request by cutthroat78**

### CODE REVIEW

**Comment by kantord** [comment]
Hi @cutthroat78 looks good to me, but there is a failure in the github check. please fix that and I'll merge it!

**Comment by kantord** [comment]
Thanks @cutthroat78 !!

**Comment by kantord** [comment]
@allcontributors please add @cutthroat78 for code

**Comment by ggadt** [comment]
@kantord Where these files have finished?

**Pull request merged**
