### PR TITLE
Major app redesign

### PR DESCRIPTION
**Pull request by sandraor**
Resolves https://github.com/LibreLingo/LibreLingo/issues/2382

Major redesign of the app UI.

### CODE REVIEW

**Comment by kantord** [comment]
Hi @sandraor :wave:

What's the source and license for the flag image? https://github.com/LibreLingo/LibreLingo/blob/c3911e9de8c43b279ba1881e2d65faba095ea59f/apps/web/static/images/flag-spanish.png

And for that matter, is there any other licensed material (images, code,etc) that we need to be aware of regarding this PR?

**Comment by sandraor** [comment]
@kantord Good point! The flag image should be removed since we're not actually using it in this iteration. The only other piece to be aware of is that this [Bulma pageloader extension](https://github.com/Wikiki/bulma-pageloader) that was used previously was copied over and modified (since Bulma is no longer used): https://github.com/LibreLingo/LibreLingo/blob/c3911e9de8c43b279ba1881e2d65faba095ea59f/apps/web/src/mystyles.scss#L574

**Comment by kantord** [comment]
> @kantord Good point! The flag image should be removed since we're not actually using it in this iteration. The only other piece to be aware of is that this [Bulma pageloader extension](https://github.com/Wikiki/bulma-pageloader) that was used previously was copied over and modified (since Bulma is no longer used):
> 
> https://github.com/LibreLingo/LibreLingo/blob/c3911e9de8c43b279ba1881e2d65faba095ea59f/apps/web/src/mystyles.scss#L574

gothca, the license for that seems to be fine. but probably I will try to reimplement everything if possible without even code copied from bulma. Although now I'm low key considering somehow merging your stuff with some of the CSS styles left in 😅 because there's still a lot of work left.

btw I started putting the refactored code here: https://github.com/LibreLingo/LibreLingo/pull/2416

**Comment by kantord** [comment]
I'm closing this in favor of this: https://github.com/LibreLingo/LibreLingo/pull/2416

sorry, the fixes are taking even longer than I thought, there's a lot to be done :sweat_smile:

**Pull request closed without merging**
