### PR TITLE
Add Low-Auvergnat

### PR DESCRIPTION
**Pull request by PrWalterB**

### CODE REVIEW

**Comment by kantord** [comment]
Hey @PrWalterB thank you!! this looks good, but courses need to be hosted in separate repos now. Let me create a new repo for this one!

**Comment by kantord** [comment]
@PrWalterB I have added you as owner of the new repo

**Comment by kantord** [comment]
I have pushed your changes into that repo after setting you as the commit author so that it's clear that you made that content! see https://github.com/LibreLingo/LibreLingo-OcAuvSept-from-FR/commit/a4d606e6b30c3924505d8e95e89166950983c468

**Comment by kantord** [comment]
Hi @PrWalterB I will close this PR as the repo is already created and your course is hosted there: https://github.com/LibreLingo/LibreLingo-OcAuvSept-from-FR

I want to set up test deployment for this course, but the CI is still failing due to basically a syntax error in one of the files. See the failure: https://github.com/LibreLingo/LibreLingo-OcAuvSept-from-FR/runs/6440341230?check_suite_focus=true

can you please fix it? if so I will set up deployment for it so that we can check it out in real life. let me know if you need help with it.

**Comment by PrWalterB** [comment]
@kantord Thanks a lot ! I wasn't sure of this. And ok, I will fix this error !

Bona jornada !

**Comment by PrWalterB** [comment]
@kantord I think the problem comes from the name "Occitan Bas-Auvergnat" I have made a commit to delete the " " between "occitan" and "bas-auvergnat". Maybe this will thix it

**Pull request closed without merging**
