### PR TITLE
Add better error message for misspelled Phrase key in yaml files, and corresponding unit test

### LINKED ISSUE #2437: When 'Phrase' is misspelled (for example 'Phase') a completely useless error message is reported
Acceptance criteria:

- When such a spelling mistake is introduced, the error message is helpful in
  * Finding out where the error is 
  * Figuring out how to fix it

Note: the error does not have to be so specific and say `You misspelled "Phrase" as "Phaser"` it's enough to say something like `Key "Phrase" not found. Keys found: "Phaser", "Translation"`

And ideally the solution to this would of course also work if it's "Translation" that's misspelled, not "Phaser" :wink: as there's reason to expect that the root of the problem is the same

### PR DESCRIPTION
**Pull request by djgoreli**
Added the suggested error message from #2437 when a "Phrase" key is misspelled in a course yaml file. Also added a unit test confirming this error message is displayed with a misspelling of the "Phrase" key.

fixes #2437

As mentioned in the follow-ups of the above issue, there was already an effective error message in place for a misspelled / missing "Translation" key so this was left as is.

### CODE REVIEW

**Comment by kantord** [comment]
Nice! At first glance looks good to me, I'll check properly soon and release it

**Comment by kantord** [comment]
Hi, the only issue is that the CI is failing due to code formatting. You can fix this by running

```bash
poetry run python black apps
```

it will format the files using [black](https://github.com/psf/black) and the pipeline will pass

**Comment by kantord** [comment]
btw did you see these failures on your fork? :thinking:

**Comment by djgoreli** [comment]
Okay, I will run the formatting locally and give the merge another shot. I was not able to see any checks / CI on my forked branch, not sure if I was looking in the wrong place or if I did something wrong in the fork setup.

**Comment by djgoreli** [comment]
Added the reformatting from running black, should be ready to run it again when you have a chance!

**Comment by kantord** [comment]
@allcontributors please add @djgoreli for code

**Comment by kantord** [comment]
@allcontributors please add @Abbi-Hackbardt for code

**Pull request merged**
